2021.09: Pulling from syword/python3-pytorch
Digest: sha256:94a36185a4cdc75b9298302e3deb78f766aa9c2ac9a71ed32bef131841e538cf
Status: Image is up to date for syword/python3-pytorch:2021.09
docker.io/syword/python3-pytorch:2021.09
Traceback (most recent call last):
  File "/my-projects/Projects/PM25_Speices_DL_2023/code/Data_Processing/derive_TrainingDatasets/main.py", line 19, in <module>
    get_save_nearest_indices(species=species)
  File "/my-projects/Projects/PM25_Speices_DL_2023/code/Data_Processing/derive_TrainingDatasets/Convert_TrainingData_pkg/Assemble_Func.py", line 12, in get_save_nearest_indices
    save_lat_lon_indices(species=species,lat_index=lat_index,lon_index=lon_index)
  File "/my-projects/Projects/PM25_Speices_DL_2023/code/Data_Processing/derive_TrainingDatasets/Convert_TrainingData_pkg/iostream.py", line 44, in save_lat_lon_indices
    np.save(lat_index_outfile, lat_index)
  File "<__array_function__ internals>", line 5, in save
  File "/opt/conda/lib/python3.9/site-packages/numpy/lib/npyio.py", line 529, in save
    format.write_array(fid, arr, allow_pickle=allow_pickle,
  File "/opt/conda/lib/python3.9/site-packages/numpy/lib/format.py", line 687, in write_array
    array.tofile(fp)
  File "/opt/conda/lib/python3.9/site-packages/numpy/ma/core.py", line 6113, in tofile
    raise NotImplementedError("MaskedArray.tofile() not implemented yet.")
NotImplementedError: MaskedArray.tofile() not implemented yet.
